[theme]
base = "dark"
primaryColor = "#00d2ff"
backgroundColor = "#0c0c0c" 
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false