# Streamlit Secrets Template
# Copy this file to .streamlit/secrets.toml and add your actual values
# DO NOT commit secrets.toml to git - it's in .gitignore

# Google Gemini API Configuration
GOOGLE_API_KEY = "your_google_api_key_here"

# Application Configuration
APP_NAME = "AI Research Paper Assistant"
DEBUG = true
MAX_UPLOAD_SIZE = 10485760  # 10MB in bytes

# Gemini Model Configuration  
GEMINI_MODEL = "gemini-1.5-flash"
GEMINI_TEMPERATURE = 0.1
GEMINI_MAX_TOKENS = 8192