# Streamlit Secrets Template
# Copy this file to .streamlit/secrets.toml and add your actual values
# DO NOT commit secrets.toml to git - it's in .gitignore

# Groq API Configuration
GROQ_API_KEY = "your_groq_api_key_here"

# Application Configuration
APP_NAME = "AI Academic Assistant"
DEBUG = true
MAX_UPLOAD_SIZE = 10485760  # 10MB in bytes

# Groq Model Configuration  
GROQ_MODEL = "llama-3.1-8b-instant"
GROQ_TEMPERATURE = 0.1
GROQ_MAX_TOKENS = 8192